name: dev_garage
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: 1.1.0
  sqflite: ^2.3.2
  path: ^1.9.0
  google_fonts: ^6.1.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_native_splash:
  color: "#121212"
  image: "assets/icon/splashLogo.png"
  android: true
  ios: false
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/iconApp.png"

